name: "publish"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-electron:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "mac"
            arch: "x64"
          - platform: "macos-latest"
            target: "mac"
            arch: "arm64"
          - platform: "ubuntu-22.04"
            target: "linux"
            arch: "x64"
          - platform: "windows-latest"
            target: "win"
            arch: "x64"
          - platform: "windows-11-arm"
            target: "win"
            arch: "arm64"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.2
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install frontend dependencies
        run: pnpm install

      - name: Build and publish Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run build:${{ matrix.target }} --publish=always
